#!/bin/sh
ppp=$1
eth=$2
hex=`ip addr show dev $eth | grep "link/ether" | awk -F ' ' '{print $2}' | awk -F ':' '{print $3$4$5$6}' `
ip=`printf '%d.%d.%d.%d\n' $(echo $hex | sed 's/../0x& /g')`
ip rule add from $ip lookup $ppp
ip route add default dev $ppp table $ppp
